build:
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
            root_path: './src'
        environment:
            php:
                version: 7.2
