build:
    project_setup:
        before:
            - "cd src"
    nodes:
        analysis:
            tests:
                override:
                    - php-scrutinizer-run
        core:
            root_path: './src'
